google formatting

diff --git a/Enter/corridor/first_chamber/.2nd_chamber/.garden_of_mitra/.room1/.shop/shopkeeper b/Enter/corridor/first_chamber/.2nd_chamber/.garden_of_mitra/.room1/.shop/shopkeeper
--- a/Enter/corridor/first_chamber/.2nd_chamber/.garden_of_mitra/.room1/.shop/shopkeeper
+++ b/Enter/corridor/first_chamber/.2nd_chamber/.garden_of_mitra/.room1/.shop/shopkeeper
@@ -2,16 +2,16 @@
 
 (return 0 2>/dev/null) && sourced=1 || sourced=0
 if [[ $sourced == 0 ]]; then
-    echo "YOU MUST SOURCE THIS SCRIPT"
-    exit 1
+  echo "YOU MUST SOURCE THIS SCRIPT"
+  exit 1
 fi
 
 if [[ -z $gold ]]; then
-    echo "YOU HAVE NOT SET YOUR GOLD VARIABLE!"
+  echo "YOU HAVE NOT SET YOUR GOLD VARIABLE!"
 fi
 
-write_dart(){
-cat <<'EOF'> dart 
+write_dart() {
+  cat <<'EOF' >dart
 Darts allow you to attack enemies from 
 
 A distance without risking your HP.
@@ -23,8 +23,8 @@ By now you should know how.
 EOF
 }
 
-write_portal(){
-cat <<'EOF'> portal
+write_portal() {
+  cat <<'EOF' >portal
 We can create symlinks (symbolic links) in linux.
 
 symlinks are shortcuts to files, binaries or directories.
@@ -49,8 +49,8 @@ eventhough its three directories behind.
 EOF
 }
 
-write_poh(){
-cat <<'EOF' > potion_of_health
+write_poh() {
+  cat <<'EOF' >potion_of_health
 Add this point, you should have two PoHs.
 
 You might want to create a dedicated variable 
@@ -67,8 +67,8 @@ You can check how many PoHs you have with:
 EOF
 }
 
-write_pom(){
-cat <<'EOF' > potion_of_magic
+write_pom() {
+  cat <<'EOF' >potion_of_magic
 The PoM comes in handy in a future room.
 
 You might want to create a dedicated variable 
@@ -85,8 +85,8 @@ You can check how many PoMs you have with:
 EOF
 }
 
-write_trick(){
-cat <<'EOF' > trick
+write_trick() {
+  cat <<'EOF' >trick
 The shell uses emacs bindings by default.
 
 Emcas is the GNU editor and its a rather complicated one.
@@ -110,44 +110,43 @@ echo -e "Welcome to the Bash Shop!\n"
 echo -e "Enter the number of the item\n"
 echo -e "Ctrl+C to exit\n"
 echo -e "What do you wish to buy?\n"
-select item in Dart Portal PoH PoM Trick
-do
-    case $item in
-        Dart)
-            price=2
-            write_dart
-            ;;
-        Portal)
-            price=4
-            write_portal
-            ;;
-        PoH)
-            price=9
-            write_poh
-            ;;
-        PoM)
-            price=10
-            write_pom
-            ;;
-        Trick)
-            price=3
-            write_trick
-            ;;
-        *)
-            echo "Invalid option. Please select a valid number."
-            continue
-            ;;
-    esac
+select item in Dart Portal PoH PoM Trick; do
+  case $item in
+    Dart)
+      price=2
+      write_dart
+      ;;
+    Portal)
+      price=4
+      write_portal
+      ;;
+    PoH)
+      price=9
+      write_poh
+      ;;
+    PoM)
+      price=10
+      write_pom
+      ;;
+    Trick)
+      price=3
+      write_trick
+      ;;
+    *)
+      echo "Invalid option. Please select a valid number."
+      continue
+      ;;
+  esac
 
-    echo "You selected $item."
-    echo "Price: $price Gold"
-    echo "Do you wish to purchase $item y/n?"
-    read -r ans
-    if [[ $ans == y ]] && [[ $gold -ge $price ]]; then
-        (( gold -= price ))
-        echo "You have $gold remaining Gold"
-    else
-        echo "You don't have enough Gold"
-        echo "Be gone, peasant!"
-    fi
+  echo "You selected $item."
+  echo "Price: $price Gold"
+  echo "Do you wish to purchase $item y/n?"
+  read -r ans
+  if [[ $ans == y ]] && [[ $gold -ge $price ]]; then
+    ((gold -= price))
+    echo "You have $gold remaining Gold"
+  else
+    echo "You don't have enough Gold"
+    echo "Be gone, peasant!"
+  fi
 done
